[package]
name = "pam-module"
version = "0.1.0"
edition = "2021"

[profile.dev]
strip = "symbols"
[profile.release]
strip = "symbols"

[lib]
name = "test_pam"
crate-type = ["cdylib"]

[dependencies]
pam = { path = "../pam" }
