[package]
name = "antenna_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17"

[profile.release]
strip = true
lto = true
opt-level = 2
